[Router] Make the target amount computation independent from non-router depositories
UXDProtocol/uxd-program pull request #287
Opened 2023-07-31 22:19 UTC by uxd-vincent

2023-07-31 22:36 UTC, uxd-vincent commented on programs/uxd/src/utils/calculate_credix_lp_depository_target_amount.rs
>  pub fn calculate_credix_lp_depository_target_amount(
this function needs a cleanup, but this could be done at a different PR later if we want

2023-08-01 04:19 UTC, acamill requested changes
This is too wild in terms of naming and quite confusing.

At this rate if we keep introducing new terms, helpers, not sure how can we maintain codebase in the future.

To provide more granular feedback:
- `let total_redeemable_amount_under_management = calculate_depositories_sum_value(&vec![`
Not so total, a depository is left out (LSD), the helper function abstract away some weird ROUTER_DEPOSITORY_COUNT, add new weird error.

I can go on but idk can you feel it or now, cause I'm often commenting these. 

I think this change is too small to warrant adding this amount of complexity/convolution to the codebase.
Also no need to make something generic before we have 2 cases. We might never have another case and LSD might not even stick, premature imo.

I would rather do: 
- keep the existing code
- where it uses `controller.redeemable_circulating_supply` replace by a new variable that is `controller.redeemable_circulating_supply - lsd_depository.redeemable_under_management`, that you can put in a getter if you prefer

Wdyt

2023-08-01 09:04 UTC, uxd-vincent commented
> This is too wild in terms of naming and quite confusing.
> 
> At this rate if we keep introducing new terms, helpers, not sure how can we maintain codebase in the future.
> 
> To provide more granular feedback:
> 
>     * `let total_redeemable_amount_under_management = calculate_depositories_sum_value(&vec![`
>       Not so total, a depository is left out (LSD), the helper function abstract away some weird ROUTER_DEPOSITORY_COUNT, add new weird error.
> 
> 
> I can go on but idk can you feel it or now, cause I'm often commenting these.
> 
> I think this change is too small to warrant adding this amount of complexity/convolution to the codebase. Also no need to make something generic before we have 2 cases. We might never have another case and LSD might not even stick, premature imo.
> 
> I would rather do:
> 
>     * keep the existing code
> 
>     * where it uses `controller.redeemable_circulating_supply` replace by a new variable that is `controller.redeemable_circulating_supply - lsd_depository.redeemable_under_management`, that you can put in a getter if you prefer
> 
> 
> Wdyt

Ah I see, so my reasoning was that I want to avoid having to inject the non-router depository into the router-related IXs so I went for using the sum of the router depositories (it's kinda like the router depositories are a pool of liquidity they share among themselves and not the other depositories).

This is to avoid having to inject the lds_depository account into the IXs:
- mint
- redeem
- rebalance_credix (2x)

Always happy to change any naming if need be, i'm not too sure what should I call those.

Do you think we should just inject the lds_depositories everywhere ?

2023-08-01 09:33 UTC, cnek commented
could use some naming like `routable_redeemable_circulating_supply` of `redeemable_circulating_supply_under_router` ?

2023-08-02 08:21 UTC, acamill commented
Hey no worries. 

Then why not add a new value in the controller that keep the circulating supply that accomodate the router? I think this simplify the whole PR more or less to that value + updating the calculation in the existing code? Wdyt

2023-08-06 11:53 UTC, uxd-vincent commented
Pausing for now since LSD is changing plans

2023-08-06 11:53 UTC, closed without merging